FIND_PATH(EV_INCLUDE_DIR NAMES ev.h)
FIND_LIBRARY(EV_LIBRARY NAMES ev)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EV DEFAULT_MSG EV_LIBRARY EV_INCLUDE_DIR)
MARK_AS_ADVANCED(EV_INCLUDE_DIR EV_LIBRARY)